import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";
import eslintConfigPrettier from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";

export default defineConfig([
  globalIgnores([
    "dist",
    "node_modules",
    "coverage",
    "tmp",
    "test_scripts",
    // Vendored verbatim from numbl — must remain byte-identical
    // (see scripts/sync_from_numbl.ts).
    "src/lexer",
    "src/parser",
    // Generated by scripts/build_runtime_snippets.ts
    "src/codegen/runtime/snippets.gen.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      eslintConfigPrettier,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.node,
    },
  },
  {
    // React-hooks rules apply only to web-app code. The translator's
    // codegen module has internal helpers named like `useRuntime` that
    // are not React hooks and would trip rules-of-hooks otherwise.
    files: [
      "src/components/**/*.{ts,tsx}",
      "src/hooks/**/*.{ts,tsx}",
      "src/pages/**/*.{ts,tsx}",
      "src/App.tsx",
      "src/main.tsx",
    ],
    extends: [reactHooks.configs.flat.recommended],
    rules: {
      // React Compiler-friendly recommendations from eslint-plugin-react-hooks
      // v7. Useful in greenfield code, but they flag intentional patterns
      // here (IndexedDB hydration via setState-in-effect; refs read from
      // debounced callbacks).
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/refs": "off",
    },
  },
]);
